### ISSUE TITLE
你好，问个问题

### ISSUE THREAD

**Issue by iosKey** [0summer0/ZXMovieBrowser#2]
我想做的效果是，选中的item放大，但是底部不是跟其他没选中一样是直的，而是比没选中的要高一些

**Comment by 0summer0** [comment]
你好哈，你说的是不是放大后上下两端要匀称那种？如果是的话，你在adjustSubviews方法里把需要放大item的frame都调整一下，y值由-(width - kItemWidth)改为-(height - kItemHeight) / 2 就可以啦，可以临时设置_scrollView.clipsToBounds = NO来看一下是不是你说的效果呢?如果是的话，在setupScrollView方法创建每个itemView时设置frame的y值为(kMovieBrowserHeight - kItemHeight) / 2

**Comment by iosWellLin** [comment]
加个qq聊聊，737292529

**Comment by iosKey** [comment]
可以加个qq聊聊吗，737292529
